/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Topic = IDL.Variant({
  'probability' : IDL.Null,
  'calculus' : IDL.Null,
  'coordinateGeometry' : IDL.Null,
  'algebra' : IDL.Null,
  'vectors' : IDL.Null,
  'trigonometry' : IDL.Null,
});
export const MathProblem = IDL.Record({
  'id' : IDL.Nat,
  'topic' : Topic,
  'question' : IDL.Text,
  'difficulty' : IDL.Nat,
  'correctAnswer' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'hasPurchasedCourse' : IDL.Bool,
});
export const Course = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isPaid' : IDL.Bool,
  'priceRupees' : IDL.Nat,
});
export const ProgressStats = IDL.Record({
  'topic' : Topic,
  'attempted' : IDL.Nat,
  'correct' : IDL.Nat,
  'accuracy' : IDL.Float64,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Time = IDL.Int;
export const Submission = IDL.Record({
  'user' : IDL.Principal,
  'attempts' : IDL.Nat,
  'isCorrect' : IDL.Bool,
  'answer' : IDL.Int,
  'problemId' : IDL.Nat,
  'timestamp' : Time,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const ValidationResult = IDL.Record({
  'correctAnswer' : IDL.Int,
  'feedback' : IDL.Text,
  'isCorrect' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMathProblem' : IDL.Func([MathProblem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllProblems' : IDL.Func([], [IDL.Vec(MathProblem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourseDetails' : IDL.Func([], [Course], ['query']),
  'getProgressByTopic' : IDL.Func([], [IDL.Vec(ProgressStats)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubmissions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseCourse' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'validateAnswer' : IDL.Func([IDL.Nat, IDL.Int], [ValidationResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Topic = IDL.Variant({
    'probability' : IDL.Null,
    'calculus' : IDL.Null,
    'coordinateGeometry' : IDL.Null,
    'algebra' : IDL.Null,
    'vectors' : IDL.Null,
    'trigonometry' : IDL.Null,
  });
  const MathProblem = IDL.Record({
    'id' : IDL.Nat,
    'topic' : Topic,
    'question' : IDL.Text,
    'difficulty' : IDL.Nat,
    'correctAnswer' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'hasPurchasedCourse' : IDL.Bool,
  });
  const Course = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isPaid' : IDL.Bool,
    'priceRupees' : IDL.Nat,
  });
  const ProgressStats = IDL.Record({
    'topic' : Topic,
    'attempted' : IDL.Nat,
    'correct' : IDL.Nat,
    'accuracy' : IDL.Float64,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'user' : IDL.Principal,
    'attempts' : IDL.Nat,
    'isCorrect' : IDL.Bool,
    'answer' : IDL.Int,
    'problemId' : IDL.Nat,
    'timestamp' : Time,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const ValidationResult = IDL.Record({
    'correctAnswer' : IDL.Int,
    'feedback' : IDL.Text,
    'isCorrect' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMathProblem' : IDL.Func([MathProblem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllProblems' : IDL.Func([], [IDL.Vec(MathProblem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourseDetails' : IDL.Func([], [Course], ['query']),
    'getProgressByTopic' : IDL.Func([], [IDL.Vec(ProgressStats)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubmissions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseCourse' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'validateAnswer' : IDL.Func([IDL.Nat, IDL.Int], [ValidationResult], []),
  });
};

export const init = ({ IDL }) => { return []; };