/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRecord {
  'paymentConfirmedAt' : [] | [Time],
  'service' : string,
  'status' : BookingStatus,
  'paymentStatus' : string,
  'date' : string,
  'name' : string,
  'time' : string,
  'paymentId' : string,
  'phone' : string,
}
export type BookingStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'awaitingPayment' : null };
export interface Course {
  'title' : string,
  'description' : string,
  'isPaid' : boolean,
  'priceRupees' : bigint,
}
export interface MathProblem {
  'id' : bigint,
  'topic' : Topic,
  'question' : string,
  'difficulty' : bigint,
  'correctAnswer' : bigint,
  'solution' : string,
}
export interface ProgressStats {
  'topic' : Topic,
  'attempted' : bigint,
  'correct' : bigint,
  'accuracy' : number,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Submission {
  'user' : Principal,
  'attempts' : bigint,
  'isCorrect' : boolean,
  'answer' : bigint,
  'problemId' : bigint,
  'timestamp' : Time,
}
export type Time = bigint;
export type Topic = { 'probability' : null } |
  { 'calculus' : null } |
  { 'coordinateGeometry' : null } |
  { 'algebra' : null } |
  { 'vectors' : null } |
  { 'trigonometry' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'hasPurchasedCourse' : boolean }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValidationResult {
  'correctAnswer' : bigint,
  'feedback' : string,
  'isCorrect' : boolean,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBookingRecord' : ActorMethod<[BookingRecord], undefined>,
  'addMathProblem' : ActorMethod<[MathProblem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getAllProblems' : ActorMethod<[], Array<MathProblem>>,
  'getBookingRecords' : ActorMethod<[], Array<BookingRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedBookings' : ActorMethod<[], Array<BookingRecord>>,
  'getCourseDetails' : ActorMethod<[], Course>,
  'getProgressByTopic' : ActorMethod<[], Array<ProgressStats>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubmissions' : ActorMethod<[Principal], Array<Submission>>,
  'hasPaidWithUPI' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markAsPaid' : ActorMethod<[string], boolean>,
  'purchaseCourse' : ActorMethod<[], undefined>,
  'recordUPIPaymentSuccessful' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'validateAnswer' : ActorMethod<[bigint, bigint], ValidationResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];